worktree-path = "{{ repo_path }}/../{{ repo }}.{{ ((branch | sanitize | split('-'))[:2]) | join('-') }}-{{ branch | hash }}"

[[pre-start]]
mise = "mise trust"

[[pre-start]]
copy = "wt step copy-ignored"

[step.copy-ignored]
exclude = ["node_modules/"]
