worktree-path = "{{ repo_path }}/../{{ repo }}.{{ ((branch | sanitize | split('-'))[:2]) | join('-') }}-{{ branch | hash }}"

[pre-start]
mise = "mise trust"

[post-start]
copy = "wt step copy-ignored"
